#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXCLUDED_PREFIXES = ("lesnicoises-v8-no-mercy-update",)

HARD_AI_MARKERS = (
    "chatgpt",
    "generated by ai",
    "ai-generated",
    "artificial intelligence",
    "language model",
    "written by ai",
)

SOFT_CLICHES = (
    "delve into",
    "vibrant tapestry",
    "seamlessly",
    "game-changer",
    "unlock the",
    "elevate your",
    "in today's fast-paced",
    "whether you're a",
    "whether you are a",
    "nestled in the heart of",
)

HOME_SEO = {
    "index.html": {
        "title": "Mametas | French Riviera travel guide",
        "description": "Plan your first French Riviera trip with a short, opinionated guide to where to stay, what to book, how to get around and what to skip.",
        "og_title": "Mametas | They know the Riviera.",
        "og_description": "A short, opinionated French Riviera guide for first-time visitors. Where to stay, what to book, how to move and what to skip.",
    },
    "fr/index.html": {
        "title": "Mametas | Guide de la Côte d’Azur",
        "description": "Préparez votre premier séjour sur la Côte d’Azur : où dormir, quoi réserver, comment circuler et ce qui ne vaut pas le détour.",
        "og_title": "Mametas | They know the Riviera.",
        "og_description": "Un guide court et décidé de la Côte d’Azur : où dormir, quoi réserver, comment circuler et ce qui ne vaut pas le détour.",
    },
}

def public_html():
    for path in ROOT.rglob("*.html"):
        rel = path.relative_to(ROOT).as_posix()
        if rel.startswith(EXCLUDED_PREFIXES):
            continue
        yield path, rel

def set_meta(text: str, *, title: str, description: str, og_title: str, og_description: str) -> str:
    text = re.sub(r"<title>.*?</title>", f"<title>{title}</title>", text, count=1, flags=re.S | re.I)
    text = re.sub(
        r'(<meta\s+name=["\']description["\']\s+content=["\'])[^"\']*(["\'])',
        lambda m: m.group(1) + description + m.group(2),
        text, count=1, flags=re.I,
    )
    text = re.sub(
        r'(<meta\s+property=["\']og:title["\']\s+content=["\'])[^"\']*(["\'])',
        lambda m: m.group(1) + og_title + m.group(2),
        text, count=1, flags=re.I,
    )
    text = re.sub(
        r'(<meta\s+property=["\']og:description["\']\s+content=["\'])[^"\']*(["\'])',
        lambda m: m.group(1) + og_description + m.group(2),
        text, count=1, flags=re.I,
    )
    return text

def remove_long_dashes(text: str) -> str:
    # Mametas deliberately avoids em/en dashes in public copy and SEO.
    # A comma reads naturally for parenthetical em-dash constructions.
    text = text.replace(" — ", ", ")
    text = text.replace("—", "-")
    # En dashes are often ranges. Keep the range meaning with a plain hyphen.
    text = text.replace(" – ", " - ")
    text = text.replace("–", "-")
    return text

def main() -> int:
    changed = 0
    removed = 0
    soft_hits = []
    hard_hits = []

    for path, rel in public_html():
        text = path.read_text(encoding="utf-8")
        before = text

        if rel in HOME_SEO:
            text = set_meta(text, **HOME_SEO[rel])

        removed += text.count("—") + text.count("–")
        text = remove_long_dashes(text)

        lower = text.lower()
        for marker in HARD_AI_MARKERS:
            if marker in lower:
                hard_hits.append((rel, marker))
        for phrase in SOFT_CLICHES:
            if phrase in lower:
                soft_hits.append((rel, phrase))

        if text != before:
            path.write_text(text, encoding="utf-8")
            changed += 1

    # Re-scan after rewriting, including title, description, Open Graph and JSON-LD.
    leftovers = []
    for path, rel in public_html():
        text = path.read_text(encoding="utf-8")
        if "—" in text or "–" in text:
            leftovers.append(rel)

    if soft_hits:
        print("Style review: generic phrases still present and worth human review:")
        for rel, phrase in sorted(set(soft_hits)):
            print(f"  {rel}: {phrase!r}")
    else:
        print("Style review: no common generic AI-copy cliches found.")

    if hard_hits:
        raise SystemExit("Public AI markers found:\n" + "\n".join(f"- {r}: {m}" for r,m in hard_hits))
    if leftovers:
        raise SystemExit("Long dashes remain in public HTML:\n- " + "\n- ".join(leftovers))

    print(f"Human-copy pass complete: {removed} long dashes removed across {changed} files.")
    print("SEO checked too: title, meta description, Open Graph and page HTML contain no long dashes or explicit AI markers.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
