#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def update(rel: str, pairs: list[tuple[str, str]]) -> None:
    path = ROOT / rel
    if not path.is_file():
        raise RuntimeError(f"Missing vous target: {rel}")
    text = path.read_text(encoding="utf-8")
    changed = 0
    for old, new in pairs:
        if old in text:
            text = text.replace(old, new)
            changed += 1
    path.write_text(text, encoding="utf-8")
    print(f"Mametas vous pass: {rel} ({changed}/{len(pairs)} replacements)")


def main() -> int:
    update("plages/index.html", [
        (
            "Si tu construis ton séjour, pars d’abord de ta base. Les plages viennent ensuite — et ça évite parfois une heure de route pour vingt minutes de sable.",
            "Si vous construisez votre séjour, partez d’abord de votre base. Les plages viennent ensuite. Et ça évite parfois une heure de route pour vingt minutes de sable.",
        ),
    ])

    update("culture/index.html", [
        ("Ne traverse pas la Côte juste pour cocher un musée.", "Ne traversez pas la Côte juste pour cocher un musée."),
        (
            "Regarde plutôt ce qui se trouve autour de ta base : la Riviera Guide rassemble culture, hôtels, plages et tables par destination.",
            "Regardez plutôt ce qui se trouve autour de votre base. Le Riviera Guide rassemble culture, hôtels, plages et tables par destination.",
        ),
    ])

    update("escapades/index.html", [
        (
            "Choisis d’abord ta base dans le Riviera Guide. Ensuite seulement, décide jusqu’où tu as envie de t’échapper.",
            "Choisissez d’abord votre base dans le Riviera Guide. Ensuite seulement, décidez jusqu’où vous avez envie de vous échapper.",
        ),
    ])

    update("lexique/index.html", [
        ("PARLE UN PEU NIÇOIS", "PARLEZ UN PEU NIÇOIS"),
        ("Exactement le genre de chose que ce site essaie de t’épargner.", "Exactement le genre de chose que ce site essaie de vous épargner."),
        ("Essaie de ne pas donner l’occasion qu’on t’appelle comme ça.", "Essayez de ne pas donner l’occasion qu’on vous appelle comme ça."),
        ("Mets-le à peu près où tu veux. Tu comprendras à l’usage.", "Mettez-le à peu près où vous voulez. Vous comprendrez à l’usage."),
        ("Ne force pas l’accent. Dégun ne t’a demandé ça.", "Ne forcez pas l’accent. Dégun ne vous a demandé ça."),
    ])

    update("riviera-guide/eze/index.html", [
        (
            "Èze est spectaculaire. Tu ne seras donc pas le seul à l’avoir remarqué. Le secret n’est pas de l’éviter, mais de bien choisir ton moment et ta manière d’y passer.",
            "Èze est spectaculaire. Vous ne serez donc pas les seuls à l’avoir remarqué. Allez-y tôt. Très tôt si c’est août. Le village est bien meilleur avant que tout le monde ait la même idée.",
        ),
        ("<h2>Commence par ça</h2>", "<h2>Commencez par ça</h2>"),
        (
            "On rassemble ici ce qui existe déjà sur Mametas pour éviter de te faire traverser le site avec une carte et une boussole.",
            "On rassemble ici ce qui existe déjà sur Mametas pour éviter de vous faire traverser le site avec une carte et une boussole.",
        ),
        (
            "Ne remplis pas chaque heure. La Côte d’Azur est beaucoup plus agréable quand on lui laisse un peu de place.",
            "Ne remplissez pas chaque heure. La Côte d’Azur est beaucoup plus agréable quand on lui laisse un peu de place.",
        ),
        (
            "Un détour voisin quand tu veux redescendre du décor de carte postale.",
            "Un détour voisin quand vous voulez redescendre du décor de carte postale.",
        ),
        (
            "Choisis une base. Garde du temps pour les détours. La Riviera punit surtout les programmes trop bien remplis.",
            "Choisissez une base. Gardez du temps pour les détours. La Riviera punit surtout les programmes trop bien remplis.",
        ),
    ])

    # About is generated by mametas_voice_pass.py before this step.
    update("a-propos/index.html", [
        (
            "Assieds-toi, pitchoun. D’abord, combien de jours tu as ? Non, tu ne fais pas Monaco, Menton et Saint-Tropez demain.",
            "Asseyez-vous, pitchoun. D’abord, combien de jours avez-vous ? Non, vous ne faites pas Monaco, Menton et Saint-Tropez demain.",
        ),
        ("<em>regarde-moi ça.</em>", "<em>regardez-moi ça.</em>"),
    ])

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
