#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Temporary diagnostic for final presentation stabilization.

Runs after the full late pipeline and canonical foundation so we can inspect
the actual homepage markup generated by the build, not only repository source.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]

PATTERNS = (
    "YOUR TRIP",
    "VOTRE SÉJOUR",
    "TRY RIVIERA FIT",
    "TESTER RIVIERA FIT",
    "TRY HOTEL FIT",
    "TESTER HOTEL FIT",
    "FILL THE DAYS",
    "REMPLIR LES JOURS",
    "SIMPLIFIED",
    "SIMPLIFIÉ",
)

for rel in ("index.html", "fr/index.html"):
    p = ROOT / rel
    s = p.read_text(encoding="utf-8", errors="ignore")
    print(f"V24 DIAGNOSTIC {rel}")
    found = False
    for pat in PATTERNS:
        m = re.search(re.escape(pat), s, flags=re.I)
        if not m:
            continue
        found = True
        lo = max(0, m.start() - 1600)
        hi = min(len(s), m.end() + 3200)
        snippet = re.sub(r"\s+", " ", s[lo:hi])
        print(f"--- {pat} ---")
        print(snippet)
    if not found:
        print("No presentation markers found.")
