#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Add canonical/hreflang metadata to the six hotel pages generated by the Explore refonte."""
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]

pairs=[
 ("hotels/nice/hotel-windsor/index.html","/hotels/nice/hotel-windsor/","/en/hotels/nice/hotel-windsor/"),
 ("hotels/beaulieu-sur-mer/la-reserve-de-beaulieu/index.html","/hotels/beaulieu-sur-mer/la-reserve-de-beaulieu/","/en/hotels/beaulieu-sur-mer/la-reserve-de-beaulieu/"),
 ("hotels/beaulieu-sur-mer/hotel-carlton/index.html","/hotels/beaulieu-sur-mer/hotel-carlton/","/en/hotels/beaulieu-sur-mer/hotel-carlton/"),
 ("hotels/beaulieu-sur-mer/hotel-select/index.html","/hotels/beaulieu-sur-mer/hotel-select/","/en/hotels/beaulieu-sur-mer/hotel-select/"),
 ("hotels/nice/mercure-nice-centre-grimaldi/index.html","/hotels/nice/mercure-nice-centre-grimaldi/","/en/hotels/nice/mercure-nice-centre-grimaldi/"),
 ("hotels/menton/riva-art-spa/index.html","/hotels/menton/riva-art-spa/","/en/hotels/menton/riva-art-spa/"),
]

def metadata(route, alt, lang):
    fr=route if lang=="fr" else alt
    en=alt if lang=="fr" else route
    canonical=fr if lang=="fr" else en
    return (
      f'<link rel="canonical" href="https://www.mametas.com{canonical}">'
      f'<link rel="alternate" hreflang="fr" href="https://www.mametas.com{fr}">'
      f'<link rel="alternate" hreflang="en" href="https://www.mametas.com{en}">'
      f'<link rel="alternate" hreflang="x-default" href="https://www.mametas.com{en}">'
    )

changed=0
for fr_path,fr_route,en_route in pairs:
    for rel,route,alt,lang in (
      (fr_path,fr_route,en_route,"fr"),
      ("en/"+fr_path,en_route,fr_route,"en"),
    ):
        p=ROOT/rel
        if not p.exists():
            raise SystemExit(f"Missing generated hotel page: {rel}")
        s=p.read_text(encoding="utf-8")
        if 'rel="canonical"' in s:
            continue
        if "</head>" not in s:
            raise SystemExit(f"Missing </head> in {rel}")
        s=s.replace("</head>",metadata(route,alt,lang)+"</head>",1)
        p.write_text(s,encoding="utf-8")
        changed+=1

print(f"Hotel canonical/hreflang patch updated {changed} generated pages")
